### ISSUE TITLE
Comparing data isn't working in State of JS 2022

### ISSUE THREAD

**Issue by etolstoy** [Devographics/Monorepo#254]
When I try to use "compare data" feature on any chart with any series, I get the following error in console:

```
Access to fetch at 'https://api2.devographics.com/graphql' from origin 'https://2022.stateofjs.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

POST https://api2.devographics.com/graphql net::ERR_FAILED

Uncaught (in promise) TypeError: Failed to fetch
    at Wn (data.ts:31:28)
    at Qr (helpers.ts:826:54)
    at GridDataLoader.tsx:40:38
    at GridDataLoader.tsx:54:13
    at Wn (react-dom.production.min.js:241:332)
    at pl (react-dom.production.min.js:285:111)
    at react-dom.production.min.js:282:343
    at cl (react-dom.production.min.js:280:396)
    at Qh (react-dom.production.min.js:272:439)
    at Os (react-dom.production.min.js:127:105)
```
<img width="950" alt="image" src="https://github.com/Devographics/Monorepo/assets/3955262/55c7dd40-9b3d-4a94-8f8a-b4b9bc412a6b">

**Comment by SachaG** [comment]
Oh right, this version isn't the latest, I switched hosts but haven't switched the DNS yet. Could you let me know if https://state-of-js-2022.onrender.com/en-US works better?

**Comment by etolstoy** [comment]
Yep, it works, thanks! 🔥

**Comment by eric-burel** [comment]
Closing as this seems ok (I am blown away by the filtering features :1st_place_medal: )
